### ISSUE TITLE
🚨 [BUG] - variadic params aren't correctly parsed

### ISSUE THREAD

**Issue by VVX7** [facebookincubator/TTPForge#250] opened 2023-08-19 02:13 UTC
### What happened?

Steps to reproduce:
1. Run variadicParameterExample.yaml

Expected behavior:
- ttpforge should parse variadic params

Actual behavior:
- ttpforge throws an exception

### Relevant log output

```shell
bash-3.2$ ttpforge run forgearmory//examples/variadic-params/variadicParameterExample.yaml -a name='foo' -a password='bar'
2023-08-18T19:33:00.736-0400	INFO	cmd/root.go:101	Using config file: /Users/vvx7/.ttpforge/config.yaml
Error: could not load TTP at /Users/vvx7/.ttpforge/repos/forgearmory/ttps/examples/variadic-params/variadicParameterExample.yaml: template: ttp:12: function "args" not defined
```
```


### Details about your environment

System Version: macOS 13.5 (22G74)
System Arch: m1
Go: go version go1.21.0 darwin/amd64 (via asdf)

**Comment by d3sch41n** [comment] 2023-08-19 02:32
Hey! Thanks very much for the report - looks like I should remove that example as it has become outdated, apologies for the confusion.  This is an updated example of how to define TTP arguments, which should work correctly:

[ttps/examples/args/define-args.yaml
](https://github.com/facebookincubator/ForgeArmory/blob/3a409f1623907f3d49f1d5ebeedf88167e431513/ttps/examples/args/define-args.yaml) 

I created the below PR to remove the deprecated example, will close this issue when it lands:

https://github.com/facebookincubator/ForgeArmory/pull/26

Thanks again for the report, happy to answer any questions!

**Comment by VVX7** [comment] 2023-08-19 02:58
Ah, ForgeArmory TTPs appear to be using the old format still. For example, [backdoor-ssh-authorized-keys](https://github.com/facebookincubator/ForgeArmory/blob/main/ttps/persistence/ssh/backdoor-ssh-authorized-keys/backdoor-ssh-authorized-keys.yaml).

**Comment by d3sch41n** [comment] 2023-08-19 04:32
Oh my, that's embarrassing - appears there was a miscommunication on our end, those were supposed to go out with the updates to the native golang template format - sincere apologies! 

Addressing in https://github.com/facebookincubator/ForgeArmory/pull/26  once I can wrangle someone to approve the PR, might be Monday since we're heading into the weekend. 

Thanks SO much for bringing that to my attention!

**Comment by l50** [comment] 2023-08-19 23:44
The fix should be merged in, thank you so much @VVX7 for sending this in! Once you've confirmed all is well and working on your end, let us know and we'll close this issue out.

**Comment by VVX7** [comment] 2023-08-20 03:56
Confirming it works, ty!

**Comment by l50** [comment] 2023-08-20 04:01
> Confirming it works, ty!

Awesome possum, closing!

**Closed by l50** 2023-08-20 04:01 UTC
Labels: bug
